apiVersion: v1
kind: Pod
metadata:
    name: nginx-label
    labels:
        team: finance
        version: 1.4.5
        environment: production
spec:
    containers:
        - name: nginx-label
          image: nginx
          ports:
            - containerPort: 80