apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: nginx-rs
    labels:
        team: finance
    annotations:
        desc: ini replicaSet finance
spec:
    replicas: 3
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
            name: nginx
            labels:
                app: nginx
        spec:
            containers:
                - name: nginx
                  image: nginx
                  ports:
                    - containerPort: 80